# SPDX-FileCopyrightText: 2020 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: MIT

on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build code
    steps:
      - uses: actions/checkout@v2
      - uses: alire-project/setup-alire@v2
      - run: alr build
